In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv(
    "../data/processed/fraud_risk_scored.csv"
)

print(df.shape)

(6362620, 33)

In [3]:
total_transactions = len(df)

print(total_transactions)

6362620

In [4]:
total_frauds = df["isFraud"].sum()

print(total_frauds)

8213

In [5]:
fraud_rate = (
    total_frauds /
    total_transactions
) * 100

print(round(fraud_rate,4))

0.1291

In [6]:
total_amount = df["amount"].sum()

print(total_amount)

1144392944759.77

In [7]:
avg_amount = df["amount"].mean()

print(avg_amount)

179861.90354913071

In [8]:
critical_alerts = (
    df["risk_category"] == "Critical"
).sum()

print(critical_alerts)

7352

In [9]:
high_risk = (
    df["risk_category"] == "High"
).sum()

print(high_risk)

732

In [10]:
investigation_required = (
    df["investigation_required"] == "Yes"
).sum()

print(investigation_required)

8084

In [11]:
review_required = (
    df["review_required"] == "Yes"
).sum()

print(review_required)

8193

In [12]:
executive_kpis = pd.DataFrame({

    "KPI": [

        "Total Transactions",
        "Fraud Transactions",
        "Fraud Rate (%)",
        "Total Transaction Amount",
        "Average Transaction Amount",
        "Critical Alerts",
        "High Risk Transactions",
        "Investigation Required",
        "Review Required"

    ],

    "Value": [

        total_transactions,
        total_frauds,
        round(fraud_rate,4),
        round(total_amount,2),
        round(avg_amount,2),
        critical_alerts,
        high_risk,
        investigation_required,
        review_required

    ]

})

executive_kpis

                          KPI         Value
0          Total Transactions  6.362620e+06
1          Fraud Transactions  8.213000e+03
2              Fraud Rate (%)  1.291000e-01
3    Total Transaction Amount  1.144393e+12
4  Average Transaction Amount  1.798619e+05
5             Critical Alerts  7.352000e+03
6      High Risk Transactions  7.320000e+02
7      Investigation Required  8.084000e+03
8             Review Required  8.193000e+03

In [13]:
executive_kpis.to_csv(
    "../data/processed/executive_kpis.csv",
    index=False
)

print("Executive KPI Dataset Saved")

Executive KPI Dataset Saved

In [14]:
executive_kpis

                          KPI         Value
0          Total Transactions  6.362620e+06
1          Fraud Transactions  8.213000e+03
2              Fraud Rate (%)  1.291000e-01
3    Total Transaction Amount  1.144393e+12
4  Average Transaction Amount  1.798619e+05
5             Critical Alerts  7.352000e+03
6      High Risk Transactions  7.320000e+02
7      Investigation Required  8.084000e+03
8             Review Required  8.193000e+03